### ISSUE TITLE
Try this

### ISSUE THREAD

**Issue by metonym** [rarar/Vibes-Extension#1]
Refs: https://stackoverflow.com/questions/18694538/sending-message-from-popup-js-in-chrome-extension-to-background-js

Based on the SO answer linked above, try the following:

```ts
// background.js

chrome.runtime.onMessage.addListener((request,sender,sendResponse) =>
{
    if( request.test) {
        chrome.tabs.query({ active: true}, (tabs) => {
            sendResponse( { text: "Hello" } );
        });        
    }
}
```

```js
// popup

chrome.runtime.sendMessage({ test: true },
        (response) => {
            console.log(response.text); // "Hello"
        });
```

**Comment by rarar** [comment]
Ah, I actually don't need to pass data from background to popup but rather
need to pass a variable to the executeScript function *all within
background.js. *If you run the extension, there's a bottom bar that will
appear on every webpage. What I need is for that bottom bar to be able to
handle a global variable (current score and avg score). Does that make
sense?

**Comment by metonym** [comment]
I stand by the comment above. I think that you need the `chrome.runtime.onMessage.addListener` API to communicate back and forth. I see that you are [already using Chrome storage to persist the running average](https://github.com/rarar/Vibes-Extension/blob/master/src/background.js#L52).

For example, using `chrome.runtime.sendMessage` in the popup would receive the response and could render it in the UI.

**Comment by metonym** [comment]
[Look into content scripts](https://stackoverflow.com/questions/9515704/use-a-content-script-to-access-the-page-context-variables-and-functions) to inject content in the page

**Comment by rarar** [comment]
The variable "avg" does not get set in inContent()

[image: image.png]

**Comment by metonym** [comment]
Maybe try the following to pass `avg` to the function:

```diff
- `(${ inContent })()`
+ `(${ inContent })( var avg = ${avg} )`
```

**Comment by metonym** [comment]
Maybe passing it as a parameter could work:

```js
`(${inContent.toString()})(${avg});`
```

```js
function inContent(avg) {
  let el = document.body.appendChild(document.createElement('div'));
  el.style.cssText = 'position:fixed; bottom:0; left:0; right:0; background:pink; text-align: center; font-size: 18px; font-family: Helvetica, sans-serif; padding: 16px;';
  el.innerHTML = 'The vibe of this page is chill' + avg;
}
```
